### ISSUE TITLE
Windows : Unexpected error javax.net.ssl.SSLHandShakeException

### ISSUE THREAD

**Issue by santhan-mastery** [andrewinci/Insulator#206]
**Describe the bug**
After installing in windows and opening insulator it gave an error as mentioned in screenshot below. Is there any prerequisites to be installed

**Screenshots**
![image](https://user-images.githubusercontent.com/85422599/127342926-18a4e4ec-eee9-4bc0-88f5-069fc27a354e.png)

**Desktop (please complete the following information):**
 - OS: Windows

**Comment by jxberrios** [comment]
> **Describe the bug**
> After installing in windows and opening insulator it gave an error as mentioned in screenshot below. Is there any prerequisites to be installed
> 
> **Screenshots**
> ![image](https://user-images.githubusercontent.com/85422599/127342926-18a4e4ec-eee9-4bc0-88f5-069fc27a354e.png)
> 
> **Desktop (please complete the following information):**
> 
> * OS: Windows

This issue also exist on MacOS. I'm helping a co-worker getting it to work and we both have the same problem.

**Comment by jxberrios** [comment]
@santhan-mastery, @troykana and I were troubleshooting this and attempted the last verified release, version 0.3.6, and it launches without hesitation.

**Comment by sidthesloth** [comment]
Hi 
Having the same issue running the latest 0.7.3 on Mac 0s Monterey is the solution to run 0.6.3? if yes does it mean the issue cannot be fixed in latest versions?
